"""Domain entities for the IAM bounded context.

This module defines the aggregate root used by the edge service to represent a
registered Restock IoT device.  Entities carry identity across their lifetime
and encapsulate state that is only modified by services enforcing domain
invariants.
"""
from datetime import datetime


class Device:
    """Aggregate root representing a registered Restock IoT device.

    A ``Device`` is the core identity object in the IAM bounded context.  It is
    identified by its MAC-address ``device_id`` and authenticated through its
    paired ``device_token``.  Device registration and lookup are managed by the
    :class:`~iam.infrastructure.repositories.DeviceRepository`.

    Attributes:
        device_id (str): Device MAC address used as public identifier.
        device_token (str): Secret token generated by cloud and used to
            authenticate HTTP requests generated by the device.
        status (str): Device lifecycle status.
        created_at (datetime): UTC timestamp recording when the device was
            first registered in the local edge database.
    """

    def __init__(
        self,
        device_id: str,
        device_token: str,
        status: str,
        created_at: datetime,
    ):
        """Initialize a Device aggregate root.

        Args:
            device_id (str): MAC-address Restock IoT device identifier.
            device_token (str): Secret token paired with the device.
            status (str): Device lifecycle status.
            created_at (datetime): UTC timestamp of device registration.
        """
        self.device_id = device_id
        self.device_token = device_token
        self.status = status
        self.created_at = created_at


class DeviceStatus:
    REGISTERED = "REGISTERED"
    CONFIGURED = "CONFIGURED"
    CALIBRATED = "CALIBRATED"
