from enum import Enum


class DisplayMode(Enum):
    """Enumeration of display modes."""

    DISPLAY_MODE_ENVIRONMENT = "DISPLAY_MODE_ENVIRONMENT"
    DISPLAY_MODE_TEMPERATURE = "DISPLAY_MODE_TEMPERATURE"
    DISPLAY_MODE_HUMIDITY = "DISPLAY_MODE_HUMIDITY"
    DISPLAY_MODE_WEIGHT = "DISPLAY_MODE_WEIGHT"
    DISPLAY_MODE_CONVERTED_UNITS = "DISPLAY_MODE_CONVERTED_UNITS"