"""Interface layer for the IAM bounded context.

Exposes a Flask Blueprint (``iam_api``) and a shared authentication helper
(``authenticate_request``) used by other bounded contexts to guard their own
endpoints.  This layer owns no domain or business logic; it is concerned with
HTTP request handling and delegation to the application service.
"""
from flask import Blueprint, jsonify, request

from iam.application.services import AuthApplicationService


iam_api = Blueprint("iam_api", __name__)

# Module-level singleton instantiated once per worker process.
auth_service = AuthApplicationService()

@iam_api.route("/api/v1/iam/devices/status", methods=["POST"])
def authenticate_request():
    """Validate the device identity for an incoming HTTP request.

    Extracts ``device_id`` from the JSON request body and ``X-API-Key`` from
    the request headers, then delegates to the IAM application service to
    verify the credentials against the local device registry.

    This helper is intended to be called at the start of any route handler in a
    bounded context that requires device authentication::

        auth_result = authenticate_request()
        if auth_result:
            return auth_result

    Expected request contract:
        - ``Content-Type: application/json`` with a body containing
          ``device_id``.
        - ``X-API-Key`` header carrying the device secret API key.

    Returns:
        tuple[flask.Response, int] | None: ``(JSON response, 401)`` when
        authentication fails; ``None`` when the request is authenticated.
    """
    device_id = request.json.get("device_id") if request.json else None
    api_key = request.headers.get("X-API-Key")

    if not device_id or not api_key:
        return jsonify({"error": "Missing device_id or X-API-Key"}), 401

    if not auth_service.device_exists(device_id):
        return jsonify({"error": "Device not registered"}), 401

    if not auth_service.authenticate(device_id, api_key):
        return jsonify({"error": "Invalid device_id or API key"}), 401

    if request.endpoint == "iam_api.authenticate_request":
        return jsonify({"success": "Device authenticated"}), 200

    return None


@iam_api.route("/api/v1/auth/sign-up", methods=["POST"])
def register_device():
    """Register a new IoT device for the local edge service.

    Expects a JSON body containing ``device_token`` generated by cloud and
    ``device_id`` containing the device MAC address.

    Idempotent: if the device is already registered, returns the existing
    record without modifying it.

    Returns:
        tuple[flask.Response, int]: ``201 Created`` with the device payload if
        newly registered, ``200 OK`` if it already existed, or
        ``400 Bad Request`` if ``device_token`` or ``device_id`` is missing.
    """
    data = request.json
    device_token = data.get("device_token") if data else None
    if device_token is None and data:
        device_token = data.get("api_key")
    device_id = data.get("device_id") if data else None

    if not isinstance(device_token, str) or not device_token.strip():
        return jsonify({"error": "Missing device_token"}), 400
    if not isinstance(device_id, str) or not device_id.strip():
        return jsonify({"error": "Missing device_id"}), 400

    device, created = auth_service.register_device(
        device_token.strip(),
        device_id.strip(),
    )
    status_code = 201 if created else 200

    return jsonify({
        "device_id": device.device_id,
        "device_token": device.device_token,
        "status": device.status,
        "created_at": device.created_at.isoformat(),
    }), status_code
